version: "3"
services:
  planetarium:
    build:
      context: .
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: 1qazcde3
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    ports:
      - "8001:8000"
    command:
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py createsuperuser --noinput || true &&
            python manage.py loaddata seed_data.json &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - mailhog

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA

  mailhog:
    image: mailhog/mailhog
    container_name: planetarium_mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  my_db:
